# For more info on HTTP files go to https://aka.ms/vs/httpfile
@Web_HostAddress = https://localhost:7145
@Email=administrator@localhost
@Password=Administrator1!
@BearerToken=<YourToken>

# POST Register
POST {{Web_HostAddress}}/v1/auth/register
Content-Type: application/json

{
  "email": "{{Email}}",
  "password": "{{Password}}"
}

###

# POST Login
POST {{Web_HostAddress}}/v1/auth/login
Content-Type: application/json

{
  "email": "{{Email}}",
  "password": "{{Password}}"
}

###

# GET Dashboard summary
GET {{Web_HostAddress}}/v1/dashboard/summary
Authorization: Bearer {{BearerToken}}

###

# GET Users
GET {{Web_HostAddress}}/v1/users?page=1&pageSize=10
Authorization: Bearer {{BearerToken}}

###

# GET Tasks
GET {{Web_HostAddress}}/v1/tasks?page=1&pageSize=10
Authorization: Bearer {{BearerToken}}

###

# GET Products
GET {{Web_HostAddress}}/v1/products?page=1&pageSize=10
Authorization: Bearer {{BearerToken}}

###

# GET Stock transactions
GET {{Web_HostAddress}}/v1/stock-transactions?page=1&pageSize=10
Authorization: Bearer {{BearerToken}}

###

# GET Conversations
GET {{Web_HostAddress}}/v1/conversations
Authorization: Bearer {{BearerToken}}

###

# GET Integrations
GET {{Web_HostAddress}}/v1/integrations
Authorization: Bearer {{BearerToken}}

###

# GET my settings
GET {{Web_HostAddress}}/v1/me/settings
Authorization: Bearer {{BearerToken}}

###
